#!/usr/bin/env bash

# Asks the user to select a directory and echos the selection

# Parse working directory to this form: /dir/subdir/
wd=$1
if [[ "$wd" != */ ]]; then
    wd+=/
fi

# Insert all directories in ${wd} and their index in items
items=()
counter=1
for file in $wd*; do
    if [[ -d $file ]]; then
        items+=( $counter $file )
        (( counter+=1 ))
    fi
done

# Show all directories in yad
yad --no-buttons --list --column=ID:NUM --column=Directory "${items[@]}" &
PID=$!

# Wait for the first yad instance to be started
sleep 0.05

# Let user enter the index of the desired directory
index="$(yad --form --field="Enter ID")"
index="${index%?}"

# Kill first yad instance
kill -9 $PID

# Retrieve desired directory from index and print it
regex='^[0-9]+$'
if [[ $index =~ $regex ]] ; then
    if [[ $index -gt 0 && $index -le $(( ${#items[@]} / 2 )) ]]; then
        echo ${items[$index * 2 - 1]}
    fi
fi
